
name: Postman

on:

  push:

jobs:
  
  run-postman-test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup Node
        uses: actions/checkout@v4
        with: 
          node-version: '16'

      - name:  Install Newman
        run: npm install -g newman

      - name:  Run Postman file on newman
        run: newman run Postman/Books.postman_collection.json -e Postman/test.postman_environment.json



    
    